site_name: 스위치 해킹 가이드
theme: slate
copyright: Copyright &copy; 2021 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Copyright &copy; 2021 <a href="https://github.com/hacks-korean" target="_blank">hacks-korean</a>, Maintained by <a href="https://github.com/hacks-korean" target="_blank">hacks-korean</a>
site_description: 스위치 커스텀 펌웨어 가이드.
site_author: NH Discord Server, hacks-korean.

nav:
    - 홈: index.md
    - 가이드:
        - '시작하기': 'user_guide/getting_started.md'
        - 'RCM': 'user_guide/rcm.md'  
        - 'RCM 진입': 'user_guide/emummc/entering_rcm.md'
        - '모드칩': 'user_guide/modchip.md'
        - '페이로드 주입': 'user_guide/emummc/sending_payload.md'      
        - 'SD 파티션 나누기': 'user_guide/emummc/partitioning_sd.md'    
        - 'SD 준비': 'user_guide/emummc/sd_preparation.md'
        - 'emuMMC(에뮤낸드) 만들기': 'user_guide/emummc/making_emummc.md'
        - '커스텀 펌웨어 실행': 'user_guide/emummc/launching_cfw.md'
    - 추가 가이드:
        - '닌텐도 서버 차단': 'extras/blocking_updates.md'
        - '낸드 백업 복원': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - '타이틀키 덤프': 'extras/dumping_title_keys.md'
        - '테마': 'extras/theming.md'
        - '세이브 관리': 'extras/save_management.md'
        - '게임 모딩': 'extras/game_modding.md'       
        - 'root 없이 Linux에서 페이로드 주입': 'extras/adding_udev.md'
        - '파일 확장자 표시 (Windows)': 'extras/showing_file_extensions.md'
        - '다른 부팅 방법': 'extras/alternate_bootsetups.md'
        - 'RCM 페이로드 인젝터 정보': 'extras/rcm_injectors.md'
        - '커스텀 펌웨어 업데이트': 'extras/updating.md'
        - 'SD 카드 바꾸기': 'extras/transfer_sd.md'
        - '용어 설명': 'extras/glossary.md'
    - FAQ: faq.md
    - About: about.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
